web.baseUrl=https://staging.femaledaily.com
web.browser=chrome

api.baseUrl=https://api-staging.femaledaily.com

android.appium.url=http://127.0.0.1:4723
android.device.name=emulator-5554
android.app.package=com.femaledaily.app
android.app.activity=.MainActivity

ios.appium.url=http://127.0.0.1:4723
ios.device.name=iPhone 16
ios.bundle.id=com.femaledaily.app
